spring.application.name=usuarios-resena

spring.datasource.url=jdbc:mysql://localhost:3306/users-resenas?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=testuser
spring.datasource.password=luis1234
# Opcional, pero bueno para asegurar que Hibernate sepa qué hacer:
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect